name: yaka2
version: 1.0.4+4
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core:
  firebase_core_platform_interface:
  firebase_messaging:
  flutter_local_notifications:

  # Core
  get:
  get_storage:
  path_provider:
  permission_handler: ^8.0.0
  restart_app:
  url_launcher:
  vibration:
  open_file_manager:
  flutter_sms_inbox: ^1.0.3

  # Video_player
  chewie: ^1.7.0
  video_player: ^2.7.2

  # usb_serial:
  android_x_storage: ^1.0.2

  # UI - Animation
  badges:
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  lottie:
  photo_view:
  pull_to_refresh:

  # Networking
  dio:
  http:

  # Utils
  flutter_iconly:
  kartal: ^4.1.0
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
#Lints
very_good_analysis: ^7.0.0
flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/image/
    - assets/videos/
    - assets/image/instruction/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300

  uses-material-design: true
