name: yaka2
version: 1.1.8+18
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: ^3.13.1
  firebase_core_platform_interface: ^5.4.0
  firebase_messaging: ^15.2.6
  awesome_notifications: ^0.10.1
  firebase_analytics: ^11.4.6
  flutter_local_notifications: ^19.2.1

  # Core
  get: ^4.7.2
  flutter_file_downloader: ^2.1.0
  get_storage: ^2.1.1
  path_provider:
  permission_handler: ^12.0.0+1
  tutorial_coach_mark: ^1.3.0
  restart_app:
  url_launcher:
  downloadsfolder: ^1.2.0
  vibration:
  flutter_sms_inbox: ^1.0.3
  webview_flutter: ^4.0.0


  # Video_player
  chewie: ^1.7.0
  sms_autofill: ^2.4.0
  video_player: ^2.7.2
  upgrader: ^11.3.2

  # UI - Animation
  badges:
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  lottie:
  photo_view:
  pull_to_refresh:

  # Networking
  dio:
  http:

  # Utils
  flutter_iconly:
  kartal: ^4.1.0
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
#Lints
very_good_analysis: ^7.0.0
flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/image/
    - assets/videos/
    - assets/image/instruction/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300

  uses-material-design: true
